package mongodb_test;

import com.mongodb.BasicDBObject;
import com.mongodb.Block;
import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import com.mongodb.client.model.Updates;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author masterx
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_animales = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_addAnimal_nombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_addAnimal_codigo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cb_addAnimal_continente = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rb_addAnimal_si = new javax.swing.JRadioButton();
        rb_addAnimal_no = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        sp_addAnimal_edad = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        tf_addAnimal_madre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_addAnimal_padre = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tf_addAnimal_veterinario = new javax.swing.JTextField();
        addAnimal = new javax.swing.JButton();
        cb_addAnimal_especie = new javax.swing.JComboBox<>();
        cb_addAnimal_subEspecie = new javax.swing.JComboBox<>();
        tf_addAnimal_pais = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        bt_buscarAnimal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_buscarAnimal = new javax.swing.JTable();
        cb_buscarAnimal1_especie = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        cb_buscarAnimal1_subespecie = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        tf_buscarAnimal_codigo = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        tf_buscarAnimal_especie = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        tf_buscarAnimal_nombre = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        tf_buscarAnimal_madre = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        tf_buscarAnimal_veterinario = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        sp_buscarAnimal_edad = new javax.swing.JSpinner();
        jLabel46 = new javax.swing.JLabel();
        tf_buscarAnimal_padre = new javax.swing.JTextField();
        rb_buscarAnimal_no = new javax.swing.JRadioButton();
        rb_buscarAnimal_si = new javax.swing.JRadioButton();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        tf_buscarAnimal_subespecie = new javax.swing.JTextField();
        cb_buscarAnimal_continente = new javax.swing.JComboBox<>();
        jLabel49 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        bt_EliminarAnimal = new javax.swing.JButton();
        bt_buscarAnimal2 = new javax.swing.JButton();
        tf_buscarAnimal_pais = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_agregarEspecie_codEspecie = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tf_agregarEspecie_nombreEspecie = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cb_agregarEspecie_codEspecie = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        tf_agregarEspecie_codSubEspecie = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tf_agregarEspecie_nombreSubEspecie = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_especies = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        lb_especies = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        cb_enfermedad_codigoAnimal = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        lb_enfermedad_nombre = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tf_enfermedad = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_enfermedad_tratamiento = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        cb_enfermedad_estado = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_enfermedades = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bt_entrarPersonal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_entrarAnimales = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bt_entrarZoologico = new javax.swing.JButton();

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jLabel5.setText("Codigo Especie");

        jLabel6.setText("Codigo Sub Especie");

        jLabel7.setText("Nombre");

        jLabel8.setText("Codigo");

        tf_addAnimal_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_addAnimal_codigoActionPerformed(evt);
            }
        });

        jLabel9.setText("Continente");

        cb_addAnimal_continente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "América", "Asia", "África", "Antártida", "Europa", "Oceanía", "Zelandia" }));
        cb_addAnimal_continente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_addAnimal_continenteItemStateChanged(evt);
            }
        });

        jLabel10.setText("Pais");

        jLabel11.setText("Nacio en Cautiverio");

        buttonGroup1.add(rb_addAnimal_si);
        rb_addAnimal_si.setText("SI");

        buttonGroup1.add(rb_addAnimal_no);
        rb_addAnimal_no.setText("NO");

        jLabel12.setText("Edad");

        sp_addAnimal_edad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));

        jLabel13.setText("Nombre de la madre");

        jLabel14.setText("Nombre del padre");

        jLabel15.setText("Cod Veterinario");

        addAnimal.setText("Agregar");
        addAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAnimalMouseClicked(evt);
            }
        });

        cb_addAnimal_especie.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_addAnimal_especieItemStateChanged(evt);
            }
        });
        cb_addAnimal_especie.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                cb_addAnimal_especieComponentMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addAnimal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tf_addAnimal_madre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel10)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tf_addAnimal_veterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(sp_addAnimal_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tf_addAnimal_padre))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cb_addAnimal_especie, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(62, 62, 62)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tf_addAnimal_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                                .addComponent(tf_addAnimal_pais))))
                                    .addGap(33, 33, 33)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rb_addAnimal_si)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rb_addAnimal_no))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cb_addAnimal_subEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(81, 81, 81))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cb_addAnimal_continente, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_addAnimal_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_addAnimal_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(cb_addAnimal_especie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_addAnimal_subEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel9)
                        .addComponent(cb_addAnimal_continente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf_addAnimal_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(rb_addAnimal_si)
                    .addComponent(rb_addAnimal_no)
                    .addComponent(tf_addAnimal_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_addAnimal_madre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tf_addAnimal_padre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(sp_addAnimal_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tf_addAnimal_veterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addAnimal)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Animal", jPanel1);

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel5ComponentShown(evt);
            }
        });

        jLabel38.setText("Especie");

        bt_buscarAnimal.setText("Buscar");
        bt_buscarAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_buscarAnimalMouseClicked(evt);
            }
        });

        tb_buscarAnimal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Especie", "Sub Eespecie", "Continente", "Pais"
            }
        ));
        jScrollPane1.setViewportView(tb_buscarAnimal);

        jLabel24.setText("Sub Especie");

        jButton6.setText("Buscar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_buscarAnimal1_especie, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_buscarAnimal1_subespecie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_buscarAnimal)
                            .addComponent(jButton6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(bt_buscarAnimal)
                    .addComponent(cb_buscarAnimal1_especie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(cb_buscarAnimal1_subespecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jTabbedPane2.addTab("Por Especie", jPanel5);

        jLabel39.setText("Codigo");

        tf_buscarAnimal_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_buscarAnimal_codigoActionPerformed(evt);
            }
        });

        jLabel40.setText("Especie");

        jLabel41.setText("Nombre");

        jLabel42.setText("Pais");

        jLabel43.setText("Madre");

        jLabel44.setText("Veterinario");

        tf_buscarAnimal_veterinario.setEnabled(false);

        jLabel45.setText("Edad");

        sp_buscarAnimal_edad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));

        jLabel46.setText("Padre");

        buttonGroup2.add(rb_buscarAnimal_no);
        rb_buscarAnimal_no.setText("NO");

        buttonGroup2.add(rb_buscarAnimal_si);
        rb_buscarAnimal_si.setText("SI");

        jLabel47.setText("Cautiverio");

        jLabel48.setText("Sub Especie");

        cb_buscarAnimal_continente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "América", "Asia", "África", "Antártida", "Europa", "Oceanía", "Zelandia" }));

        jLabel49.setText("Continente");

        jButton9.setText("Guardar Cambio");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        bt_EliminarAnimal.setText("Eliminar");
        bt_EliminarAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_EliminarAnimalMouseClicked(evt);
            }
        });

        bt_buscarAnimal2.setText("Buscar");
        bt_buscarAnimal2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_buscarAnimal2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_buscarAnimal_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_buscarAnimal2))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel42))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_buscarAnimal_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(tf_buscarAnimal_especie)
                                    .addComponent(tf_buscarAnimal_pais))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel48)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_buscarAnimal_subespecie, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel49)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cb_buscarAnimal_continente, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(17, 17, 17)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_buscarAnimal_si)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_buscarAnimal_no))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_buscarAnimal_veterinario))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_buscarAnimal_madre, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_buscarAnimal_padre, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sp_buscarAnimal_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_EliminarAnimal)))
                .addGap(0, 112, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(tf_buscarAnimal_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_buscarAnimal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(tf_buscarAnimal_especie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_buscarAnimal_subespecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_buscarAnimal_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel49)
                    .addComponent(cb_buscarAnimal_continente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jLabel47)
                    .addComponent(rb_buscarAnimal_si)
                    .addComponent(rb_buscarAnimal_no)
                    .addComponent(tf_buscarAnimal_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(tf_buscarAnimal_madre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46)
                    .addComponent(tf_buscarAnimal_padre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(tf_buscarAnimal_veterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45)
                    .addComponent(sp_buscarAnimal_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(bt_EliminarAnimal))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Por Identificador", jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Buscar", jPanel2);

        jTabbedPane3.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel4ComponentShown(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Especie");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Sub Especie");

        jLabel18.setText("Codigo Especie");

        jLabel19.setText("Nombre");

        jLabel20.setText("Codigo Especie");

        jLabel21.setText("Codigo SubEspecie");

        jLabel22.setText("Nombre");

        jButton1.setText("Agregar Especie");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Agregar SubEspecie");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_agregarEspecie_codEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_agregarEspecie_nombreEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addGap(85, 85, 85)))
                        .addGap(9, 9, 9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_agregarEspecie_codSubEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_agregarEspecie_codEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_agregarEspecie_nombreSubEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel17))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addGap(63, 63, 63))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(tf_agregarEspecie_codEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(tf_agregarEspecie_nombreEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(cb_agregarEspecie_codEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(tf_agregarEspecie_codSubEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel22)
                                .addComponent(tf_agregarEspecie_nombreSubEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Agregar", jPanel4);

        jButton3.setText("Especies");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        tb_especies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tb_especies);

        jButton4.setText("Sub Especies");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Eliminar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        lb_especies.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(lb_especies)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lb_especies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Eliminar", jPanel9);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Especie/Sub Especie", jPanel3);

        jTabbedPane4.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel8.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel8ComponentShown(evt);
            }
        });

        jLabel25.setText("Codigo del Animal");

        cb_enfermedad_codigoAnimal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_enfermedad_codigoAnimalItemStateChanged(evt);
            }
        });
        cb_enfermedad_codigoAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_enfermedad_codigoAnimalMouseClicked(evt);
            }
        });

        jLabel26.setText("Nombre del Animal:");

        lb_enfermedad_nombre.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lb_enfermedad_nombre.setText("------------");

        jLabel28.setText("Enfermedad");

        jLabel29.setText("Tratamiento");

        ta_enfermedad_tratamiento.setColumns(20);
        ta_enfermedad_tratamiento.setRows(5);
        jScrollPane3.setViewportView(ta_enfermedad_tratamiento);

        jLabel30.setText("Estado");

        cb_enfermedad_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enfermo", "Curado" }));

        jButton7.setText("Agregar");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_enfermedad_codigoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(18, 18, 18)
                                .addComponent(tf_enfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_enfermedad_nombre))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_enfermedad_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton7))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(cb_enfermedad_codigoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(lb_enfermedad_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tf_enfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(cb_enfermedad_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addGap(39, 39, 39))
        );

        jTabbedPane4.addTab("Nuevas", jPanel8);

        jPanel10.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel10ComponentShown(evt);
            }
        });

        tb_enfermedades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tb_enfermedades);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Lista", jPanel10);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Enfermedades", jPanel7);

        javax.swing.GroupLayout jd_animalesLayout = new javax.swing.GroupLayout(jd_animales.getContentPane());
        jd_animales.getContentPane().setLayout(jd_animalesLayout);
        jd_animalesLayout.setHorizontalGroup(
            jd_animalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_animalesLayout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jd_animalesLayout.setVerticalGroup(
            jd_animalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, Short.MAX_VALUE)
        );

        jLabel23.setText("jLabel23");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Sistema de Mantenimiento del Zoologico de Cordoba");

        bt_entrarPersonal.setText("Entrar");

        jLabel2.setText("Personal:");

        jLabel3.setText("Animales:");

        bt_entrarAnimales.setText("Entrar");
        bt_entrarAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_entrarAnimalesMouseClicked(evt);
            }
        });

        jLabel4.setText("Zoologico:");

        bt_entrarZoologico.setText("Entrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_entrarPersonal)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bt_entrarZoologico, javax.swing.GroupLayout.PREFERRED_SIZE, 62, Short.MAX_VALUE)
                                .addComponent(bt_entrarAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bt_entrarPersonal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bt_entrarAnimales))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bt_entrarZoologico))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_addAnimal_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_addAnimal_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_addAnimal_codigoActionPerformed

    private void tf_buscarAnimal_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_buscarAnimal_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_buscarAnimal_codigoActionPerformed

    private void addAnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAnimalMouseClicked
        // TODO add your handling code here:
        MongoClientURI uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        MongoClient zoo = new MongoClient(uri);
        MongoDatabase db = zoo.getDatabase(uri.getDatabase());
        Document doc = new Document();
        doc.append("CodigoAnimal", Integer.parseInt(this.tf_addAnimal_codigo.getText()));
        doc.append("CodigoEspecie", Integer.parseInt(this.cb_addAnimal_especie.getSelectedItem().toString()));
        doc.append("CodigoSubEspecie", Integer.parseInt(this.cb_addAnimal_subEspecie.getSelectedItem().toString()));
        doc.append("Nombre", this.tf_addAnimal_nombre.getText());
        doc.append("Continente", this.cb_addAnimal_continente.getSelectedItem().toString());
        doc.append("Pais", this.tf_addAnimal_pais.getText());
        doc.append("Nombre_Madre", this.tf_addAnimal_madre.getText());
        doc.append("Nombre_Padre", this.tf_addAnimal_padre.getText());
        if (this.rb_addAnimal_si.isSelected()) {
            doc.append("Cautiverio", "SI");
        } else {
            doc.append("Cautiverio", "NO");
        }
        doc.append("CodigoVeterinario", Integer.parseInt(this.tf_addAnimal_veterinario.getText()));
        doc.append("Edad", this.sp_addAnimal_edad.getValue());
        db.getCollection("Animales").insertOne(doc);
        JOptionPane.showMessageDialog(this, "Agregado con Exito");
        this.tf_addAnimal_codigo.setText("");
        this.cb_addAnimal_especie.setSelectedIndex(1);
        this.cb_addAnimal_subEspecie.setSelectedIndex(1);
        this.tf_addAnimal_nombre.setText("");
        this.tf_addAnimal_madre.setText("");
        this.tf_addAnimal_padre.setText("");
        this.tf_addAnimal_veterinario.setText("");
        this.cb_addAnimal_continente.setSelectedIndex(1);
        this.tf_addAnimal_pais.setText("");
        this.rb_addAnimal_no.setSelected(false);
        this.sp_addAnimal_edad.setValue(0);
    }//GEN-LAST:event_addAnimalMouseClicked

    private void bt_entrarAnimalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_entrarAnimalesMouseClicked
        // TODO add your handling code here:
        dialog(this.jd_animales);
    }//GEN-LAST:event_bt_entrarAnimalesMouseClicked

    private void bt_buscarAnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_buscarAnimalMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Especie");
        modelo.addColumn("Sub Especie");
        modelo.addColumn("Continente");
        modelo.addColumn("Pais");

        MongoClientURI uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        MongoClient zoo = new MongoClient(uri);
        MongoDatabase db = zoo.getDatabase(uri.getDatabase());
        BasicDBObject query = new BasicDBObject();
        query.put("CodigoEspecie", Integer.parseInt(this.cb_buscarAnimal1_especie.getSelectedItem().toString()));
        FindIterable<Document> iterable = db.getCollection("Animales").find(query);
        iterable.forEach(new Block<Document>() {
            @Override
            public void apply(final Document doc) {
                Object[] a = {doc.get("CodigoAnimal"), doc.get("Nombre"), doc.get("CodigoEspecie"), doc.get("CodigoSubEspecie"), doc.get("Continente"), doc.get("Pais")};
                modelo.addRow(a);
            }
        });
        this.tb_buscarAnimal.setModel(modelo);

    }//GEN-LAST:event_bt_buscarAnimalMouseClicked

    private void bt_buscarAnimal2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_buscarAnimal2MouseClicked
        // TODO add your handling code here:
        MongoClientURI uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        MongoClient zoo = new MongoClient(uri);
        MongoDatabase db = zoo.getDatabase(uri.getDatabase());
        BasicDBObject query = new BasicDBObject();
        query.put("CodigoAnimal", Integer.parseInt(this.tf_buscarAnimal_codigo.getText()));
        Document doc = db.getCollection("Animales").find(query).first();
        this.tf_buscarAnimal_especie.setText(doc.get("CodigoEspecie").toString());
        this.tf_buscarAnimal_subespecie.setText(doc.get("CodigoSubEspecie").toString());
        this.tf_buscarAnimal_nombre.setText(doc.get("Nombre").toString());
        this.tf_buscarAnimal_madre.setText(doc.get("Nombre_Madre").toString());
        this.tf_buscarAnimal_padre.setText(doc.get("Nombre_Padre").toString());
        this.tf_buscarAnimal_veterinario.setText(doc.get("CodigoVeterinario").toString());
        this.cb_buscarAnimal_continente.setSelectedItem(doc.get("Continente"));
        this.tf_buscarAnimal_pais.setText(doc.get("Pais").toString());
        this.sp_buscarAnimal_edad.setValue(doc.get("Edad"));
        if (doc.get("Cautiverio").toString().equals("SI")) {
            this.rb_buscarAnimal_si.setSelected(true);
        } else {
            this.rb_buscarAnimal_no.setSelected(true);
        }
    }//GEN-LAST:event_bt_buscarAnimal2MouseClicked

    private void bt_EliminarAnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_EliminarAnimalMouseClicked
        // TODO add your handling code here:
        MongoClientURI uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        MongoClient zoo = new MongoClient(uri);
        MongoDatabase db = zoo.getDatabase(uri.getDatabase());
        int opcion;
        try {
            opcion = JOptionPane.showConfirmDialog(this.jd_animales, "¿Desea Borrarlo?", "Borrar", YES_NO_OPTION);
            if (opcion == 0) {
                db.getCollection("Animales").deleteOne(Filters.eq("CodigoAnimal", this.tf_buscarAnimal_codigo.getText()));
                JOptionPane.showMessageDialog(this.jd_animales, "Eliminado!");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_EliminarAnimalMouseClicked

    private void cb_addAnimal_continenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_addAnimal_continenteItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_addAnimal_continenteItemStateChanged

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        MongoClientURI uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        MongoClient zoo = new MongoClient(uri);
        MongoDatabase db = zoo.getDatabase(uri.getDatabase());
        int codigo = Integer.parseInt(this.tf_buscarAnimal_codigo.getText());
        db.getCollection("Animales").updateOne(Filters.eq("CodigoAnimal", codigo), Updates.set("CodigoEspecie", Integer.parseInt(this.tf_buscarAnimal_especie.getText())));
        db.getCollection("Animales").updateOne(Filters.eq("CodigoAnimal", codigo), Updates.set("Nombre", this.tf_buscarAnimal_nombre.getText()));
        db.getCollection("Animales").updateOne(Filters.eq("CodigoAnimal", codigo), Updates.set("CodigoSubEspecie", Integer.parseInt(this.tf_buscarAnimal_subespecie.getText())));
        db.getCollection("Animales").updateOne(Filters.eq("CodigoAnimal", codigo), Updates.set("Continente", this.cb_buscarAnimal_continente.getSelectedItem().toString()));
        db.getCollection("Animales").updateOne(Filters.eq("CodigoAnimal", codigo), Updates.set("Pais", this.tf_buscarAnimal_pais.getText()));
        db.getCollection("Animales").updateOne(Filters.eq("CodigoAnimal", codigo), Updates.set("Edad", this.sp_buscarAnimal_edad.getValue()));
        db.getCollection("Animales").updateOne(Filters.eq("CodigoAnimal", codigo), Updates.set("Nombre_Madre", this.tf_buscarAnimal_madre.getText()));
        db.getCollection("Animales").updateOne(Filters.eq("CodigoAnimal", codigo), Updates.set("Nombre_Padre", this.tf_buscarAnimal_padre.getText()));
        if (this.rb_buscarAnimal_si.isSelected()) {
            db.getCollection("Animales").updateOne(Filters.eq("CodigoAnimal", codigo), Updates.set("Cautiverio", "SI"));
        } else {
            db.getCollection("Animales").updateOne(Filters.eq("CodigoAnimal", codigo), Updates.set("Cautiverio", "NO"));
        }
        JOptionPane.showMessageDialog(this.jd_animales, "Modificado Exitosamente!");
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        MongoClientURI uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        MongoClient zoo = new MongoClient(uri);
        MongoDatabase db = zoo.getDatabase(uri.getDatabase());
        Document doc = new Document();
        BasicDBObject query = new BasicDBObject();
        query.put("CodigoEspecie", Integer.parseInt(this.tf_agregarEspecie_codEspecie.getText()));
        Document doc2 = db.getCollection("Especie").find(query).first();
        System.out.println(doc2);
        if (doc2 == null) {
            doc.append("CodigoEspecie", Integer.parseInt(this.tf_agregarEspecie_codEspecie.getText()));
            doc.append("NombreEspecie", this.tf_agregarEspecie_nombreEspecie.getText());
            db.getCollection("Especie").insertOne(doc);
            JOptionPane.showMessageDialog(this.jd_animales, "Agregado con Exito");
            this.tf_agregarEspecie_codEspecie.setText("");
            this.tf_agregarEspecie_nombreEspecie.setText("");
        } else {
            JOptionPane.showMessageDialog(this.jd_animales, "El codigo de la especie ya existe...");
        }

        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        FindIterable<Document> iterable = db.getCollection("Especie").find();
        iterable.forEach(new Block<Document>() {
            @Override
            public void apply(final Document document) {
                modelo.addElement(document.get("CodigoEspecie"));
                System.out.println(document);
            }
        });
        this.cb_agregarEspecie_codEspecie.setModel(modelo);

    }//GEN-LAST:event_jButton1MouseClicked

    private void jPanel4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel4ComponentShown
        // TODO add your handling code here:
        MongoClientURI uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        MongoClient zoo = new MongoClient(uri);
        MongoDatabase db = zoo.getDatabase(uri.getDatabase());
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        FindIterable<Document> iterable = db.getCollection("Especie").find();
        iterable.forEach(new Block<Document>() {
            @Override
            public void apply(final Document document) {
                modelo.addElement(document.get("CodigoEspecie"));
            }
        });
        this.cb_agregarEspecie_codEspecie.setModel(modelo);
    }//GEN-LAST:event_jPanel4ComponentShown

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        MongoClientURI uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        MongoClient zoo = new MongoClient(uri);
        MongoDatabase db = zoo.getDatabase(uri.getDatabase());
        Document doc = new Document();
        BasicDBObject query = new BasicDBObject();
        query.put("CodigoSubEspecie", Integer.parseInt(this.tf_agregarEspecie_codSubEspecie.getText()));
        if (db.getCollection("SubEspecie").find(query).first() == null) {
            doc.append("CodigoEspecie", Integer.parseInt(this.cb_agregarEspecie_codEspecie.getSelectedItem().toString()));
            doc.append("CodigoSubEspecie", Integer.parseInt(this.tf_agregarEspecie_codSubEspecie.getText()));
            doc.append("NombreSubEspecie", this.tf_agregarEspecie_nombreSubEspecie.getText());
            db.getCollection("SubEspecie").insertOne(doc);
            JOptionPane.showMessageDialog(this.jd_animales, "Agregado con Exito");
            this.tf_agregarEspecie_codSubEspecie.setText("");
            this.tf_agregarEspecie_nombreSubEspecie.setText("");
            this.cb_agregarEspecie_codEspecie.setSelectedIndex(1);
        } else {
            JOptionPane.showMessageDialog(this.jd_animales, "El codigo de la SubEspecie ya existe...");
        }

    }//GEN-LAST:event_jButton2MouseClicked

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
        MongoClientURI uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        MongoClient zoo = new MongoClient(uri);
        MongoDatabase db = zoo.getDatabase(uri.getDatabase());
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        FindIterable<Document> iterable = db.getCollection("Especie").find();
        iterable.forEach(new Block<Document>() {
            @Override
            public void apply(final Document document) {
                modelo.addElement(document.get("CodigoEspecie"));
            }
        });
        this.cb_addAnimal_especie.setModel(modelo);
        cb_buscarAnimal1_especie.setModel(modelo);
    }//GEN-LAST:event_jPanel1ComponentShown

    private void cb_addAnimal_especieComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cb_addAnimal_especieComponentMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_addAnimal_especieComponentMoved

    private void cb_addAnimal_especieItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_addAnimal_especieItemStateChanged
        // TODO add your handling code here:
        MongoClientURI uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        MongoClient zoo = new MongoClient(uri);
        MongoDatabase db = zoo.getDatabase(uri.getDatabase());
        BasicDBObject query = new BasicDBObject();
        query.put("CodigoEspecie", Integer.parseInt(this.cb_addAnimal_especie.getSelectedItem().toString()));
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        FindIterable<Document> iterable = db.getCollection("SubEspecie").find(query);
        iterable.forEach(new Block<Document>() {
            @Override
            public void apply(final Document document) {
                modelo.addElement(document.get("CodigoSubEspecie"));
            }
        });
        this.cb_addAnimal_subEspecie.setModel(modelo);
    }//GEN-LAST:event_cb_addAnimal_especieItemStateChanged

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo Especie");
        modelo.addColumn("Nombre");

        MongoClientURI uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        MongoClient zoo = new MongoClient(uri);
        MongoDatabase db = zoo.getDatabase(uri.getDatabase());

        FindIterable<Document> iterable = db.getCollection("Especie").find();
        iterable.forEach(new Block<Document>() {
            @Override
            public void apply(final Document doc) {
                Object[] a = {doc.get("CodigoEspecie"), doc.get("NombreEspecie")};
                modelo.addRow(a);
            }
        });
        this.tb_especies.setModel(modelo);
        lb_especies.setText("Especies");
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo Especie");
        modelo.addColumn("Codigo Sub Especie");
        modelo.addColumn("Nombre");

        MongoClientURI uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        MongoClient zoo = new MongoClient(uri);
        MongoDatabase db = zoo.getDatabase(uri.getDatabase());

        FindIterable<Document> iterable = db.getCollection("SubEspecie").find();
        iterable.forEach(new Block<Document>() {
            @Override
            public void apply(final Document doc) {
                Object[] a = {doc.get("CodigoEspecie"), doc.get("CodigoSubEspecie"), doc.get("NombreSubEspecie")};
                modelo.addRow(a);
            }
        });
        this.tb_especies.setModel(modelo);
        lb_especies.setText("Sub Especies");
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        MongoClientURI uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        MongoClient zoo = new MongoClient(uri);
        MongoDatabase db = zoo.getDatabase(uri.getDatabase());
        int opcion;
        if (lb_especies.getText().equals("Especies")) {
            int codigoEspecie = (int) this.tb_especies.getValueAt(tb_especies.getSelectedRow(), 1);
            try {
                opcion = JOptionPane.showConfirmDialog(this.jd_animales, "¿Desea Borrarlo?", "Borrar", YES_NO_OPTION);
                if (opcion == 0) {
                    db.getCollection("Especie").deleteOne(Filters.eq("CodigoEspecie", codigoEspecie));
                    JOptionPane.showMessageDialog(this.jd_animales, "Eliminado!");
                }
            } catch (Exception e) {
            }
        } else {
            int codigoEspecie = (int) this.tb_especies.getValueAt(tb_especies.getSelectedRow(), 1);
            try {
                opcion = JOptionPane.showConfirmDialog(this.jd_animales, "¿Desea Borrarlo?", "Borrar", YES_NO_OPTION);
                if (opcion == 0) {
                    db.getCollection("SubEspecie").deleteOne(Filters.eq("CodigoSubEspecie", codigoEspecie));
                    JOptionPane.showMessageDialog(this.jd_animales, "Eliminado!");
                }
            } catch (Exception e) {
            }
        }

    }//GEN-LAST:event_jButton5MouseClicked

    private void jPanel5ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel5ComponentShown
        // TODO add your handling code here:
        MongoClientURI uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        MongoClient zoo = new MongoClient(uri);
        MongoDatabase db = zoo.getDatabase(uri.getDatabase());
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        FindIterable<Document> iterable = db.getCollection("SubEspecie").find();
        iterable.forEach(new Block<Document>() {
            @Override
            public void apply(final Document document) {
                modelo.addElement(document.get("CodigoSubEspecie"));
            }
        });
        this.cb_buscarAnimal1_subespecie.setModel(modelo);
    }//GEN-LAST:event_jPanel5ComponentShown

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Especie");
        modelo.addColumn("Sub Especie");
        modelo.addColumn("Continente");
        modelo.addColumn("Pais");

        MongoClientURI uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        MongoClient zoo = new MongoClient(uri);
        MongoDatabase db = zoo.getDatabase(uri.getDatabase());
        BasicDBObject query = new BasicDBObject();
        query.put("CodigSuboEspecie", Integer.parseInt(this.cb_buscarAnimal1_subespecie.getSelectedItem().toString()));
        FindIterable<Document> iterable = db.getCollection("Animales").find(query);
        iterable.forEach(new Block<Document>() {
            @Override
            public void apply(final Document doc) {
                Object[] a = {doc.get("CodigoAnimal"), doc.get("Nombre"), doc.get("CodigoEspecie"), doc.get("CodigoSubEspecie"), doc.get("Continente"), doc.get("Pais")};
                modelo.addRow(a);
            }
        });
        this.tb_buscarAnimal.setModel(modelo);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jPanel8ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel8ComponentShown
        // TODO add your handling code here:
        MongoClientURI uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        MongoClient zoo = new MongoClient(uri);
        MongoDatabase db = zoo.getDatabase(uri.getDatabase());
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        FindIterable<Document> iterable = db.getCollection("Animales").find();
        iterable.forEach(new Block<Document>() {
            @Override
            public void apply(final Document document) {
                modelo.addElement(document.get("CodigoAnimal"));
            }
        });
        this.cb_enfermedad_codigoAnimal.setModel(modelo);
    }//GEN-LAST:event_jPanel8ComponentShown

    private void cb_enfermedad_codigoAnimalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_enfermedad_codigoAnimalItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_enfermedad_codigoAnimalItemStateChanged

    private void cb_enfermedad_codigoAnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_enfermedad_codigoAnimalMouseClicked
        // TODO add your handling code here:
        MongoClientURI uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        MongoClient zoo = new MongoClient(uri);
        MongoDatabase db = zoo.getDatabase(uri.getDatabase());
        BasicDBObject query = new BasicDBObject();
        query.put("CodigoAnimal", Integer.parseInt(this.cb_enfermedad_codigoAnimal.getSelectedItem().toString()));
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        Document doc = db.getCollection("Animales").find(query).first();
        this.lb_enfermedad_nombre.setText(doc.get("Nombre") + "");
    }//GEN-LAST:event_cb_enfermedad_codigoAnimalMouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        MongoClientURI uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        MongoClient zoo = new MongoClient(uri);
        MongoDatabase db = zoo.getDatabase(uri.getDatabase());
        Document doc = new Document();
        BasicDBObject query = new BasicDBObject();
        query.put("NombreEnfermedad", this.tf_enfermedad.getText());
        Document doc2 = db.getCollection("Enfermedades").find(query).first();
        if (doc2 == null) {
            doc.append("CodigoAnimal", Integer.parseInt(cb_enfermedad_codigoAnimal.getSelectedItem().toString()));
            doc.append("NombreEnfermedad", this.tf_enfermedad.getText());
            doc.append("Tratamiento", this.ta_enfermedad_tratamiento.getText());
            doc.append("Estado", cb_enfermedad_estado.getSelectedItem().toString());
            db.getCollection("Enfermedades").insertOne(doc);
            JOptionPane.showMessageDialog(this.jd_animales, "Agregado con Exito");
            this.tf_enfermedad.setText("");
            this.ta_enfermedad_tratamiento.setText("");
        } else {
            JOptionPane.showMessageDialog(this.jd_animales, "La enfermedad ya existe...");
        }

    }//GEN-LAST:event_jButton7MouseClicked

    private void jPanel10ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel10ComponentShown
        // TODO add your handling code here:
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo Animal");
        modelo.addColumn("Enfermedad");
        modelo.addColumn("Tratamiento");
        modelo.addColumn("Estado");
        MongoClientURI uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        MongoClient zoo = new MongoClient(uri);
        MongoDatabase db = zoo.getDatabase(uri.getDatabase());
        FindIterable<Document> iterable = db.getCollection("Enfermedades").find();
        iterable.forEach(new Block<Document>() {
            @Override
            public void apply(final Document doc) {
                Object[] a = {doc.get("CodigoAnimal"), doc.get("NombreEnfermedad"),doc.get("Tratamiento"),doc.get("Estado")};
                modelo.addRow(a);
            }
        });
        this.tb_enfermedades.setModel(modelo);
    }//GEN-LAST:event_jPanel10ComponentShown
    public void dialog(JDialog a) {
        a.setModal(true);
        a.pack();
        a.setLocationRelativeTo(this);
        a.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAnimal;
    private javax.swing.JButton bt_EliminarAnimal;
    private javax.swing.JButton bt_buscarAnimal;
    private javax.swing.JButton bt_buscarAnimal2;
    private javax.swing.JButton bt_entrarAnimales;
    private javax.swing.JButton bt_entrarPersonal;
    private javax.swing.JButton bt_entrarZoologico;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_addAnimal_continente;
    private javax.swing.JComboBox<String> cb_addAnimal_especie;
    private javax.swing.JComboBox<String> cb_addAnimal_subEspecie;
    private javax.swing.JComboBox<String> cb_agregarEspecie_codEspecie;
    private javax.swing.JComboBox<String> cb_buscarAnimal1_especie;
    private javax.swing.JComboBox<String> cb_buscarAnimal1_subespecie;
    private javax.swing.JComboBox<String> cb_buscarAnimal_continente;
    private javax.swing.JComboBox<String> cb_enfermedad_codigoAnimal;
    private javax.swing.JComboBox<String> cb_enfermedad_estado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JDialog jd_animales;
    private javax.swing.JLabel lb_enfermedad_nombre;
    private javax.swing.JLabel lb_especies;
    private javax.swing.JRadioButton rb_addAnimal_no;
    private javax.swing.JRadioButton rb_addAnimal_si;
    private javax.swing.JRadioButton rb_buscarAnimal_no;
    private javax.swing.JRadioButton rb_buscarAnimal_si;
    private javax.swing.JSpinner sp_addAnimal_edad;
    private javax.swing.JSpinner sp_buscarAnimal_edad;
    private javax.swing.JTextArea ta_enfermedad_tratamiento;
    private javax.swing.JTable tb_buscarAnimal;
    private javax.swing.JTable tb_enfermedades;
    private javax.swing.JTable tb_especies;
    private javax.swing.JTextField tf_addAnimal_codigo;
    private javax.swing.JTextField tf_addAnimal_madre;
    private javax.swing.JTextField tf_addAnimal_nombre;
    private javax.swing.JTextField tf_addAnimal_padre;
    private javax.swing.JTextField tf_addAnimal_pais;
    private javax.swing.JTextField tf_addAnimal_veterinario;
    private javax.swing.JTextField tf_agregarEspecie_codEspecie;
    private javax.swing.JTextField tf_agregarEspecie_codSubEspecie;
    private javax.swing.JTextField tf_agregarEspecie_nombreEspecie;
    private javax.swing.JTextField tf_agregarEspecie_nombreSubEspecie;
    private javax.swing.JTextField tf_buscarAnimal_codigo;
    private javax.swing.JTextField tf_buscarAnimal_especie;
    private javax.swing.JTextField tf_buscarAnimal_madre;
    private javax.swing.JTextField tf_buscarAnimal_nombre;
    private javax.swing.JTextField tf_buscarAnimal_padre;
    private javax.swing.JTextField tf_buscarAnimal_pais;
    private javax.swing.JTextField tf_buscarAnimal_subespecie;
    private javax.swing.JTextField tf_buscarAnimal_veterinario;
    private javax.swing.JTextField tf_enfermedad;
    // End of variables declaration//GEN-END:variables
}
